// import 'dart:async';
// import 'dart:ffi';
// import 'dart:ui';
// import 'dart:html';

// import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:mop_green/chartDashboard/chart1dash.dart';
import 'package:mop_green/chartDashboard/chart2dash.dart';
import 'package:mop_green/chartDashboard/chart3dash.dart';
import 'package:mop_green/chartDashboard/chart4dash.dart';
import 'package:mop_green/chartLogview/chart1log.dart';
import 'package:mop_green/chartLogview/chart2log.dart';
import 'package:mop_green/chartLogview/chart3log.dart';
import 'package:mop_green/chartLogview/chart4log.dart';
import 'package:mop_green/shared/shared.dart';
import 'package:syncfusion_flutter_gauges/gauges.dart';
import 'package:convex_bottom_bar/convex_bottom_bar.dart';
import 'package:avatar_view/avatar_view.dart';
import 'package:dropdown_search/dropdown_search.dart';
// import 'package:auto_size_text/auto_size_text.dart';

part 'selamatdatang_pages.dart';
part 'dashboard.dart';
part 'log_view.dart';
part 'user.dart';
part 'navigasi.dart';
part 'profil.dart';
part 'about_us.dart';
part 'map.dart';
